todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todoapp.urls"))
]

todoapp/urls.py
from django.urls import path
from .views import todo_view, update_todo_view, delete_todo_view, add_todo_view

app_name = "todoapp"
urlpatterns = [
    path("", todo_view, name="todo_view"),
    path("add-todo/", add_todo_view, name="add_todo_view"),
    path("update-todo/<int:todo_id>/", update_todo_view,  name="update_todo_view"),
    path("delete-todo/<int:todo_id>/", delete_todo_view,  name="delete_todo_view")
    
]

todoapp/models.py
from django.db import models


class Todo(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    completed = models.BooleanField(default=False)
    date_added = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    

todoapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

from .models import Todo


def todo_view(request):        
    todos = Todo.objects.all()
    context = {"todos": todos}
    return render(request, "index.html", context)


def add_todo_view(request):
    if request.method == "POST":
        name = request.POST.get("item")
        if name:
            todo = Todo()
            todo.name = name
            todo.save()
            messages.error(request, f"Successfully added {name}.")
            return redirect("todoapp:todo_view")
        else:
            messages.error(request, "Please enter an item name")
    return render(request, "add_todo.html")


def update_todo_view(request, todo_id):
    item_to_update = Todo.objects.get(id=todo_id)
    if request.method == "POST":
        todo_name = request.POST.get("item")
        
        item_to_update.name = todo_name
        item_to_update.save()
        
        messages.info(request, "Item updated successful")
        return redirect("todoapp:todo_view")
    context = {"item_to_update": item_to_update}
    return render(request, "update_todo.html", context)


def delete_todo_view(request, todo_id):
    Todo.objects.get(id=todo_id).delete()
    
    messages.info(request, "Item was deleted successfully!")
    return redirect("todoapp:todo_view")

templates/add_todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Todo</title>
</head>
<body>
    <form action="{% url 'todoapp:add_todo_view' %}" method="post">
        <label>Add an Item</label>
        {% csrf_token %}
        {% for msg in messages %}
            <div>{{msg}}</div>
        {% endfor %}
        <input type="text" name="item" id="">
        <button type="submit">Add</button>
    </form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Items</title>
</head>
<body>

    <div>
        <a href="{% url 'todoapp:add_todo_view' %}">
            <button>Add Item</button>
        </a>
        <table>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Date</th>
                <th>Completed</th>
            </tr>
            {% for todo in todos %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{todo.name}}</td>
                <td>{{todo.date_added}}</td>
                <td>{{todo.completed}}</td>
                <td><a href="{% url 'todoapp:update_todo_view' todo.id %}"><button style="background-color: green;">Update</button></a></td>
                <td><a href="{% url 'todoapp:delete_todo_view' todo.id %}"><button style="background-color: red;">Delete</button></a></td>
            </tr>
            {% endfor %}
        </table>

    </div>
</body>
</html>

templates/update_todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
</head>
<body>
    <form action="{% url 'todoapp:update_todo_view' item_to_update.id%}" method="post">
        <label>updating {{item_to_update.name}} </label>
        {% csrf_token %}
            
        {% for msg in messages %}
        <p style="color: red;">{{ msg }}</p>
        {% endfor %}
        <input type="text" name="item" id="" value="{{item_to_update.name}}">
        <button type="submit">Update</button>
        <p>item ID: {{item_to_update.id}}</p>
        <p>item name: {{item_to_update.name}}</p>
        <p>date added: {{item_to_update.date_added}}</p>
        <p>completed: {{item_to_update.completed}}</p>
    </form>

</body>
</html>